/// Commands that get an autogenerated `allow-*` permission.
///
/// Tauri's ACL only covers plugin commands. Phase 0 verified that the
/// loopback-served UI can call `plugin:app|version` but is rejected for an
/// application command (`desktop_probe not allowed. Plugin not found`), so
/// anything the UI has to reach lives here instead.
const COMMANDS: &[&str] = &["desktop_status", "restart_service"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
